import type { Language } from './presentation';

const en = {
  skip: 'Skip to main content',
  navLabel: 'Primary navigation',
  home: 'Home',
  about: 'About',
  projects: 'Projects',
  contact: 'Contact',
  menuOpen: 'Open navigation menu',
  menuClose: 'Close navigation menu',
  language: 'Language',
  english: 'English',
  turkish: 'Turkish',
  useDarkTheme: 'Use dark theme',
  useLightTheme: 'Use light theme',
  heroKicker: 'GAMEPLAY PROGRAMMER · UNITY DEVELOPER',
  heroStatus: 'AVAILABLE FOR NEW CHALLENGES',
  heroTitleStart: 'Building responsive',
  heroTitleAccent: 'gameplay experiences',
  heroTitleEnd: 'with Unity.',
  exploreProjects: 'Explore projects',
  meetDeveloper: 'Meet the developer',
  viewCv: 'View CV',
  featuredEyebrow: 'Featured release',
  featuredTitle: 'Latest production',
  featuredDescription: 'A highlighted shipped title from the portfolio.',
  projectsEyebrow: 'Project archive',
  projectsTitle: 'Selected work',
  projectsDescription: 'Playable ideas, technical studies and compact game demos built around clear systems.',
  filterLabel: 'Filter projects by technology',
  filterAll: 'All',
  resultOne: 'Showing 1 project.',
  resultMany: 'Showing {count} projects.',
  resultZero: 'No projects match this filter.',
  role: 'Role',
  developer: 'Developer',
  publisher: 'Publisher',
  released: 'Released',
  technologies: 'Technologies',
  ctaPlay: 'Play',
  ctaStore: 'Store page',
  ctaSource: 'Source code',
  ctaInfo: 'More information',
  externalLink: 'opens in a new tab',
  skillsEyebrow: 'Tool loadout',
  skillsTitle: 'Skills and tools',
  skillsDescription: 'The core tools I use to take gameplay from prototype to a maintainable build.',
  experienceEyebrow: 'Campaign log',
  experienceTitle: 'Experience',
  experienceDescription: 'Professional Unity work, internships and computer engineering education.',
  profileEyebrow: 'Player profile',
  profileTitle: 'Games have always been part of my life.',
  readAbout: 'Read more about me',
  contactEyebrow: 'Open channel',
  contactTitle: 'Let’s build something that feels good to play.',
  contactDescription: 'For game development opportunities, collaborations or a conversation about Unity, send me a message.',
  emailMe: 'Email me',
  socialProfiles: 'Social profiles',
  footerNote: 'Gameplay programmer and Unity developer.',
  aboutEyebrow: 'About the developer',
  aboutTitle: 'I turn game ideas into readable, responsive systems.',
  aboutIntro: 'My work centers on Unity gameplay development, prototyping and the details that make interaction feel intentional.',
  aboutFocusLabel: 'Current focus',
  aboutFocus: 'Game development',
  aboutExperienceLabel: 'Unity experience',
  aboutExperience: 'About six years',
  aboutProfessionalLabel: 'Professional experience',
  aboutProfessional: 'Two years in industry',
  aboutJourneyEyebrow: 'Journey',
  aboutJourneyTitle: 'Experience and education',
} as const;

const tr: { [Key in keyof typeof en]: string } = {
  skip: 'Ana içeriğe geç',
  navLabel: 'Ana navigasyon',
  home: 'Ana Sayfa',
  about: 'Hakkımda',
  projects: 'Projeler',
  contact: 'İletişim',
  menuOpen: 'Navigasyon menüsünü aç',
  menuClose: 'Navigasyon menüsünü kapat',
  language: 'Dil',
  english: 'İngilizce',
  turkish: 'Türkçe',
  useDarkTheme: 'Koyu temayı kullan',
  useLightTheme: 'Açık temayı kullan',
  heroKicker: 'OYNANIŞ PROGRAMCISI · UNITY GELİŞTİRİCİSİ',
  heroStatus: 'YENİ FIRSATLARA AÇIK',
  heroTitleStart: 'Unity ile akıcı',
  heroTitleAccent: 'oynanış deneyimleri',
  heroTitleEnd: 'geliştiriyorum.',
  exploreProjects: 'Projeleri keşfet',
  meetDeveloper: 'Geliştiriciyi tanı',
  viewCv: 'CV’yi görüntüle',
  featuredEyebrow: 'Öne çıkan yapım',
  featuredTitle: 'En yeni yapım',
  featuredDescription: 'Portfolyoda öne çıkan yayımlanmış bir oyun.',
  projectsEyebrow: 'Proje arşivi',
  projectsTitle: 'Seçili çalışmalar',
  projectsDescription: 'Anlaşılır sistemler etrafında geliştirilen oynanabilir fikirler, teknik çalışmalar ve küçük oyun demoları.',
  filterLabel: 'Projeleri teknolojiye göre filtrele',
  filterAll: 'Tümü',
  resultOne: '1 proje gösteriliyor.',
  resultMany: '{count} proje gösteriliyor.',
  resultZero: 'Bu filtreyle eşleşen proje yok.',
  role: 'Rol',
  developer: 'Geliştirici',
  publisher: 'Yayıncı',
  released: 'Yayın yılı',
  technologies: 'Teknolojiler',
  ctaPlay: 'Oyna',
  ctaStore: 'Mağaza sayfası',
  ctaSource: 'Kaynak kodu',
  ctaInfo: 'Daha fazla bilgi',
  externalLink: 'yeni sekmede açılır',
  skillsEyebrow: 'Araç seti',
  skillsTitle: 'Yetenekler ve araçlar',
  skillsDescription: 'Oynanışı prototipten sürdürülebilir bir yapıya taşırken kullandığım temel araçlar.',
  experienceEyebrow: 'Görev günlüğü',
  experienceTitle: 'Deneyim',
  experienceDescription: 'Profesyonel Unity çalışmaları, stajlar ve bilgisayar mühendisliği eğitimi.',
  profileEyebrow: 'Oyuncu profili',
  profileTitle: 'Oyunlar her zaman hayatımın bir parçası oldu.',
  readAbout: 'Hakkımda daha fazlası',
  contactEyebrow: 'Açık kanal',
  contactTitle: 'Oynaması keyifli bir şey geliştirelim.',
  contactDescription: 'Oyun geliştirme fırsatları, iş birlikleri veya Unity üzerine konuşmak için bana mesaj gönderin.',
  emailMe: 'E-posta gönder',
  socialProfiles: 'Sosyal profiller',
  footerNote: 'Oynanış programcısı ve Unity geliştiricisi.',
  aboutEyebrow: 'Geliştirici hakkında',
  aboutTitle: 'Oyun fikirlerini anlaşılır ve akıcı sistemlere dönüştürüyorum.',
  aboutIntro: 'Çalışmalarım Unity oynanış geliştirme, prototipleme ve etkileşimi bilinçli hissettiren ayrıntılara odaklanıyor.',
  aboutFocusLabel: 'Güncel odak',
  aboutFocus: 'Oyun geliştirme',
  aboutExperienceLabel: 'Unity deneyimi',
  aboutExperience: 'Yaklaşık altı yıl',
  aboutProfessionalLabel: 'Profesyonel deneyim',
  aboutProfessional: 'Endüstride iki yıl',
  aboutJourneyEyebrow: 'Yolculuk',
  aboutJourneyTitle: 'Deneyim ve eğitim',
};

export type UiCopy = { [Key in keyof typeof en]: string };

export function getUiCopy(language: Language): UiCopy {
  return language === 'tr' ? tr : en;
}
