siteTitle:
  en: Noyan Berkay Aşkın | Game Developer Portfolio
  tr: Noyan Berkay Aşkın | Oyun Geliştirici Portfolyosu
siteDescription:
  en: The game development portfolio of Noyan Berkay Aşkın, featuring Unity projects and professional experience.
  tr: Noyan Berkay Aşkın'ın Unity projelerini ve profesyonel deneyimini içeren oyun geliştirme portfolyosu.
siteUrl: https://vitoleone.github.io
socials:
  - label: GitHub
    url: https://github.com/Vitoleone
  - label: LinkedIn
    url: https://www.linkedin.com/in/noyan-berkay-askin-616a75224/
